"""Extract mania sprites from a Night05 (.osk) skin folder into our assets/sprites/.

Night05 ships per-column sprites (note1 for outer, note2 for inner); this v1
extractor picks the outer-column versions for all columns. A future per-column
asset map would let us match Night05's exact column color scheme.

Usage:
    python scripts/extract_night05_sprites.py <path-to-extracted-osk-dir>

Example:
    python scripts/extract_night05_sprites.py \\
        "/var/mnt/Synology-Reddie/Mania ORDR Bot/skins/_default/_default-source"
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

DEST = Path(__file__).resolve().parent.parent / "osu_mania_renderer_v2" / "assets" / "sprites"

# Map our atlas slot name → list of candidate filenames in Night05.
# We pick the first one that exists. @2x variants preferred for sharper output.
MAPPING: dict[str, list[str]] = {
    # Notes — per column (1=outer, 2=inner, S=center)
    "note_tap_outer":          ["mania-note1@2x.png", "mania-note1.png"],
    "note_tap_inner":          ["mania-note2@2x.png", "mania-note2.png"],
    "note_tap_center":         ["mania-noteS@2x.png", "mania-noteS.png"],
    "note_hold_head_outer":    ["mania-note1H@2x.png", "mania-note1H.png"],
    "note_hold_head_inner":    ["mania-note2H@2x.png", "mania-note2H.png"],
    "note_hold_head_center":   ["mania-noteSH@2x.png", "mania-noteSH.png"],
    "note_hold_body_outer":    ["mania-note1L@2x.png", "mania-note1L.png"],
    "note_hold_body_inner":    ["mania-note2L@2x.png", "mania-note2L.png"],
    "note_hold_body_center":   ["mania-noteSL@2x.png", "mania-noteSL.png"],
    "note_hold_tail_outer":    ["mania-note1T@2x.png", "mania-note1T.png"],
    "note_hold_tail_inner":    ["mania-note2T@2x.png", "mania-note2T.png"],
    "note_hold_tail_center":   ["mania-noteST@2x.png", "mania-noteST.png"],
    # Receptors are kept as procedural hollow-circle sprites (generated by
    # scripts/generate_placeholder_sprites.py) so they match the web-viewer
    # look. Night05's bar-style mania-key sprites are intentionally skipped.
    # Stage decoration
    "stage_left":              ["mania-stage-left@2x.png", "mania-stage-left.png"],
    "stage_right":             ["mania-stage-right@2x.png", "mania-stage-right.png"],
    "stage_light":             ["mania-stage-light@2x.png", "mania-stage-light.png"],
    # Effects + misc.
    # NOTE: column_bg keeps its placeholder (solid dark rect) — Night05's
    # mania-stage-bottom is a thin bottom strip and stretches badly.
    "hit_light":               ["lightingL@2x.png", "lightingL.png",
                                "lighting@2x.png", "lighting.png"],
    # Judgments
    "judgment_geki":           ["mania-hit300g@2x.png", "mania-hit300g.png"],
    "judgment_300":            ["mania-hit300@2x.png", "mania-hit300.png"],
    "judgment_katu":           ["mania-hit200@2x.png", "mania-hit200.png"],
    "judgment_100":            ["mania-hit100@2x.png", "mania-hit100.png"],
    "judgment_50":             ["mania-hit50@2x.png", "mania-hit50.png"],
    "judgment_miss":           ["mania-hit0@2x.png", "mania-hit0.png"],
}


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: extract_night05_sprites.py <extracted-osk-dir>",
              file=sys.stderr)
        return 2
    src = Path(sys.argv[1])
    if not src.is_dir():
        print(f"not a directory: {src}", file=sys.stderr)
        return 1

    copied = 0
    missing: list[str] = []
    for slot, candidates in MAPPING.items():
        chosen = None
        for fn in candidates:
            cand = src / fn
            if cand.is_file():
                chosen = cand
                break
        if chosen is None:
            missing.append(slot)
            continue
        out = DEST / f"{slot}.png"
        shutil.copy2(chosen, out)
        print(f"  {slot:18s} ← {chosen.name}")
        copied += 1

    if missing:
        print()
        print(f"WARNING: no Night05 source found for {len(missing)} slot(s):")
        for s in missing:
            print(f"  - {s}  (keeping placeholder)")
        print("These will continue using the placeholder sprites from "
              "scripts/generate_placeholder_sprites.py.")
    print(f"\nDone. Copied {copied}/{len(MAPPING)} slots to {DEST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
